font_family      jetbrains mono nerd font
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto

mouse_hide_wait  2.0
cursor_shape     block

# default text and background
foreground              #BBCCFF 
background              #110511


url_color        #0087bd
url_style        dotted

background_opacity 0.5
background_blur 1

hide_window_decorations yes
window_padding_width    0
window_border_width     1 
window_margin_width     0
draw_minimal_borders    yes

scrollbar_gap 0.0

# Tab bar
tab_bar_min_tabs            2
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_margin_width        0.0
tab_bar_margin_height       0.0 0.0

active_tab_foreground   #282844
active_tab_background   #8888FF

inactive_tab_foreground #BBCCFF
inactive_tab_background #282844
tab_bar_background      #110511
tab_bar_margin_color    #110511

# Kitty window border colors
active_border_color     none
inactive_border_color   #8899BB
bell_border_color       #8899BB

# highlighted text
selection_foreground    #282844
selection_background    #9999BB

# Cursor colors
cursor                  #BBCCFF 
cursor_text_color       #282844

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8

