# Favorite characters for unicode input
# Enter the hex code for each favorite character on a new line. Blank lines are
# ignored and anything after a # is considered a comment.

# box drawing regular
2500 # ─
2502 # │
250C # ┌
2510 # ┐
2514 # └
2518 # ┘
251C # ├
2524 # ┤
252C # ┬
2534 # ┴
253C # ┼

# box drawing bold
2501 # ━
2503 # ┃
250F # ┏
2513 # ┓
2517 # ┗
251B # ┛
2523 # ┣
252B # ┫
2533 # ┳
253B # ┻
254B # ╋


