#!/usr/bin/bash

#start swwww
swww query || swww-daemon & disown

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
if [ $THEMEIS == "dark.css" ]; then
	swww img ~/.config/hypr/wallpaper-dark.jpg
    swww img ~/.config/hypr/wallpaper-dark.gif
else
    swww img ~/.config/hypr/wallpaper.jpg
fi
