#!/bin/bash

handle() {
  case $1 in monitoradded*)
    ~/.config/hypr/scripts/bgaction
  esac
  case $1 in monitorremoved*)
    ~/.config/hypr/scripts/bgaction
  esac
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" | while read -r line; do handle "$line"; done


