#!/bin/sh

# most of this script does nothing, it just sets dark mode so its commented out

#ln -sf ~/.config/waybar/style/style-dark.css ~/.config/waybar/style.css
#killall -SIGUSR2 waybar
#
#ln -sf ~/.config/wofi/style/style-dark.css ~/.config/wofi/style.css
#
#xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
#xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita-dark"
#
#gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
#gsettings set org.gnome.desktop.interface icon-theme "Adwaita-dark"
#
## i like the light theme for sddm :)
#ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

# check background and switch
CURR_BACKGROUND=$(swww query | cut -d '/' -f7)
NEW_BACKGROUND="wallpaper-dark.jpg"
if [ $CURR_BACKGROUND == "wallpaper-dark.jpg" ]; then
	NEW_BACKGROUND="wallpaper-dark.gif"
fi
swww img ~/.config/hypr/$NEW_BACKGROUND --transition-fps 60 --transition-type any --transition-duration 2


exit


# original script from SolDoesTech below

## Check which waybar theme is set
#THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)
#
##if the theme is not dark then we need to switch to it
#if [ $THEMEIS != "dark.css" ]; then
#    SWITCHTO="-dark"
#fi
#
##set the waybar theme
#ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css
#
##set the wofi theme
#ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css
#
##set the xfce theme
#xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
#xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"
#
##set the GTK theme
#gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
#gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"
#
##change the background image and be cool about it ;)
#swww img ~/.config/hypr/wallpaper$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
#
##update the sddm image
#ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
#
##restart the waybar
#killall -SIGUSR2 waybar
